export const DUVIRI_FRAMES = [
  [
    '/Lotus/Language/Suits/InfestationName',
    '/Lotus/Language/Suits/BardName',
    '/Lotus/Language/Suits/PriestName',
  ],
  [
    '/Lotus/Language/Suits/GlassName',
    '/Lotus/Language/Suits/KhoraName',
    '/Lotus/Language/Suits/RevenantName',
  ],
  [
    '/Lotus/Language/Suits/GarudaName',
    '/Lotus/Language/Suits/PacifistName',
    '/Lotus/Language/Suits/IronFrameName',
  ],
  [
    '/Lotus/Language/Suits/ExcaliburName',
    '/Lotus/Language/Suits/TrinityName',
    '/Lotus/Language/Suits/EmberName',
  ],
  [
    '/Lotus/Language/Suits/LokiName',
    '/Lotus/Language/Suits/MagName',
    '/Lotus/Language/Suits/RhinoName',
  ],
  [
    '/Lotus/Language/Suits/AshName',
    '/Lotus/Language/Suits/FrostName',
    '/Lotus/Language/Suits/NyxName',
  ],
  [
    '/Lotus/Language/Suits/SarynName',
    '/Lotus/Language/Suits/VaubanName',
    '/Lotus/Language/Suits/NovaName',
  ],
  [
    '/Lotus/Language/Suits/NekrosName',
    '/Lotus/Language/Suits/ValkyrName',
    '/Lotus/Language/Suits/OberonName',
  ],
  [
    '/Lotus/Language/Suits/HydroidName',
    '/Lotus/Language/Suits/MirageName',
    '/Lotus/Language/Suits/LimboName',
  ],
  [
    '/Lotus/Language/Suits/MesaName',
    '/Lotus/Language/Suits/ChromaName',
    '/Lotus/Language/Suits/AtlasName',
  ],
  [
    '/Lotus/Language/Suits/IvaraName',
    '/Lotus/Language/Suits/InarosName',
    '/Lotus/Language/Suits/TitaniaName',
  ],
]

export const DUVIRI_WEAPONS = [
  [
    '/Lotus/Language/Items/AutoShotgunName',
    '/Lotus/Language/Items/ReconnasorName',
    '/Lotus/Language/Items/CorpusHandRocketLauncherName',
    '/Lotus/Language/Items/HeavyRifleName',
    '/Lotus/Language/Items/ParisScytheName',
  ],
  [
    '/Lotus/Language/Items/StaffName',
    '/Lotus/Language/Items/SemiAutoRifleName',
    '/Lotus/Language/Items/AutoPistolName',
    '/Lotus/Language/Items/FistName',
    '/Lotus/Language/Items/ShotgunName',
  ],
  [
    '/Lotus/Language/Locations/Lex',
    '/Lotus/Language/Items/PaladinMaceName',
    '/Lotus/Language/Items/BoltoRifleName',
    '/Lotus/Language/Items/HandCannonName',
    '/Lotus/Language/Items/CeramicDaggerName',
  ],
  [
    '/Lotus/Language/ClanTech/Torid',
    '/Lotus/Language/Items/InfestedLexName',
    '/Lotus/Language/Weapons/InfestedDualAxeName',
    '/Lotus/Language/Items/GrineerSawbladeGunName',
    '/Lotus/Language/Items/GrnHeatGunName',
  ],
  [
    '/Lotus/Language/Items/RegorAxeShieldName',
    '/Lotus/Language/Items/TennoAssaultRifleName',
    '/Lotus/Language/Items/TennoRevolverName',
    '/Lotus/Language/Items/NamiSoloName',
    '/Lotus/Language/Items/BurstRifleName',
  ],
  [
    '/Lotus/Language/Weapons/SybarisPistolName',
    '/Lotus/Language/Items/IceHammerName',
    '/Lotus/Language/Items/StalkerBowName',
    '/Lotus/Language/Items/StalkerKunaiName',
    '/Lotus/Language/Items/StalkerScytheName',
  ],
  [
    '/Lotus/Language/Items/EnergyRifleName',
    '/Lotus/Language/Items/TennoLeverActionRifleName',
    '/Lotus/Language/Items/CorpusMinigunName',
    '/Lotus/Language/Items/BurstPistolName',
    '/Lotus/Language/Items/TennoSaiName',
  ],
  [
    '/Lotus/Language/Items/RifleName',
    '/Lotus/Language/Items/PistolName',
    '/Lotus/Language/Items/LongSwordName',
    '/Lotus/Language/Items/HuntingBowName',
    '/Lotus/Language/Items/KunaiName',
  ],
]
